"""empty message

Revision ID: 0e99b21f114a
Revises: 383fd5a5ea01
Create Date: 2024-07-15 20:10:01.151338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e99b21f114a'
down_revision: Union[str, None] = '383fd5a5ea01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('last_activity', sa.DateTime(), nullable=True, comment='когда клиент авторизовался'))
    op.add_column('sessions', sa.Column('host', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'host')
    op.drop_column('sessions', 'last_activity')
    # ### end Alembic commands ###
