"""empty message

Revision ID: 130df351cf27
Revises: 7d1fb6329472
Create Date: 2024-06-20 20:20:19.574428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '130df351cf27'
down_revision: Union[str, None] = '7d1fb6329472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=64), nullable=True, comment='токен авторизации'),
    sa.Column('sms_code', sa.String(length=16), nullable=True, comment='Код из смски'),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True, comment='когда клиент авторизовался'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_sessions_token'), 'raw_sessions', ['token'], unique=False)
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=False)
    op.add_column('raports', sa.Column('uuid', sa.String(length=36), nullable=True))
    op.add_column('raports', sa.Column('raw_data', sa.JSON(), nullable=True))
    op.add_column('raports', sa.Column('requests_count', sa.Integer(), nullable=True, comment='колличество запросов файла'))
    op.create_index(op.f('ix_raports_uuid'), 'raports', ['uuid'], unique=False)
    op.drop_column('raports', 'pattern')
    op.create_index(op.f('ix_sessions_token'), 'sessions', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_token'), table_name='sessions')
    op.add_column('raports', sa.Column('pattern', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False, comment='ссылка на название шаблона'))
    op.drop_index(op.f('ix_raports_uuid'), table_name='raports')
    op.drop_column('raports', 'requests_count')
    op.drop_column('raports', 'raw_data')
    op.drop_column('raports', 'uuid')
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.drop_index(op.f('ix_raw_sessions_token'), table_name='raw_sessions')
    op.drop_table('raw_sessions')
    # ### end Alembic commands ###
