"""empty message

Revision ID: 1573d65fb7b5
Revises: e2f61985cc18
Create Date: 2024-06-28 11:44:49.205822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1573d65fb7b5'
down_revision: Union[str, None] = 'e2f61985cc18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raports', sa.Column('hidden', sa.Boolean(), nullable=True, comment='Флаг скрывает файл из выдачи'))
    op.drop_column('raports', 'exists')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raports', sa.Column('exists', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True, comment='Флаг отвечает существование файла в файловой системе, не удалять, потому что отчет можно восстановить по raw_data'))
    op.drop_column('raports', 'hidden')
    # ### end Alembic commands ###
