"""empty message

Revision ID: 25eaf42df639
Revises: eb5f073d8e54
Create Date: 2024-06-28 11:32:47.354672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '25eaf42df639'
down_revision: Union[str, None] = 'eb5f073d8e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raports_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=128), nullable=True),
    sa.Column('value', sa.String(length=256), nullable=True),
    sa.Column('raport_id', sa.Integer(), nullable=True, comment='ссылка на рапорт'),
    sa.ForeignKeyConstraint(['raport_id'], ['raports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('raports', 'raw_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raports', sa.Column('raw_data', mysql.JSON(), nullable=True, comment='сырая информация от клиента'))
    op.drop_table('raports_data')
    # ### end Alembic commands ###
