"""empty message

Revision ID: 281e135970fc
Revises: e5769ed72f06
Create Date: 2024-06-20 23:08:07.939331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '281e135970fc'
down_revision: Union[str, None] = 'e5769ed72f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raports', sa.Column('exists', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raports', 'exists')
    # ### end Alembic commands ###
