"""empty message

Revision ID: 716027b5bbd9
Revises: 0f3eccdd2b36
Create Date: 2024-07-15 19:52:25.944891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '716027b5bbd9'
down_revision: Union[str, None] = '0f3eccdd2b36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('join_at', sa.DateTime(), nullable=True, comment='когда клиент присоеденился к системе'))
    op.drop_column('clients', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('date', mysql.DATETIME(), nullable=True, comment='когда клиент присоеденился к системе'))
    op.drop_column('clients', 'join_at')
    # ### end Alembic commands ###
