"""empty message

Revision ID: 7571db2ea71e
Revises: d660ede04ea8
Create Date: 2024-06-20 17:19:14.474050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7571db2ea71e'
down_revision: Union[str, None] = 'd660ede04ea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raports', sa.Column('client_id', sa.Integer(), nullable=True, comment='ссылка на клиента'))
    op.create_foreign_key(None, 'raports', 'clients', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'raports', type_='foreignkey')
    op.drop_column('raports', 'client_id')
    # ### end Alembic commands ###
