"""empty message

Revision ID: 7d1fb6329472
Revises: 7571db2ea71e
Create Date: 2024-06-20 18:51:32.327893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d1fb6329472'
down_revision: Union[str, None] = '7571db2ea71e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raports', sa.Column('name', sa.String(length=128), nullable=False, comment='Читаемое название рапорта'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raports', 'name')
    # ### end Alembic commands ###
