"""empty message

Revision ID: 99124e90d518
Revises: 
Create Date: 2024-06-20 13:43:09.337404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99124e90d518'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True, comment='имя клиента'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='номер телефона клиента'),
    sa.Column('date', sa.DateTime(), nullable=True, comment='когда клиент присоеденился к системе'),
    sa.Column('blocked', sa.Boolean(), nullable=True, comment='флаг о блокировке, на будущее'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=64), nullable=True, comment='токен авторизации'),
    sa.Column('client_id', sa.Integer(), nullable=True, comment='ссылка на клиента'),
    sa.Column('date', sa.DateTime(), nullable=True, comment='когда клиент авторизовался'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    op.drop_table('clients')
    # ### end Alembic commands ###
