"""empty message

Revision ID: 9a590c5a6f3a
Revises: fe3c0b3ac673
Create Date: 2024-07-14 23:43:50.206722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9a590c5a6f3a'
down_revision: Union[str, None] = 'fe3c0b3ac673'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_raw_sessions_token', table_name='raw_sessions')
    op.drop_table('raw_sessions')
    op.add_column('sessions', sa.Column('sms_code', sa.String(length=10), nullable=False))
    op.add_column('sessions', sa.Column('verefied', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'verefied')
    op.drop_column('sessions', 'sms_code')
    op.create_table('raw_sessions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', mysql.VARCHAR(length=64), nullable=True, comment='токен авторизации'),
    sa.Column('sms_code', mysql.VARCHAR(length=16), nullable=True, comment='Код из смски'),
    sa.Column('phone', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('date', mysql.DATETIME(), nullable=True, comment='когда клиент авторизовался'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_raw_sessions_token', 'raw_sessions', ['token'], unique=False)
    # ### end Alembic commands ###
