"""empty message

Revision ID: 9c12dd3946d6
Revises: 281e135970fc
Create Date: 2024-06-20 23:21:12.988522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9c12dd3946d6'
down_revision: Union[str, None] = '281e135970fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raports', 'uuid',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment='уникальный ключ рапорта',
               existing_nullable=True)
    op.alter_column('raports', 'exists',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Флаг отвечает существование файла в файловой системе, не удалять, потому что отчет можно восстановить по raw_data',
               existing_nullable=True)
    op.alter_column('raports', 'raw_data',
               existing_type=mysql.JSON(),
               comment='сырая информация от клиента',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raports', 'raw_data',
               existing_type=mysql.JSON(),
               comment=None,
               existing_comment='сырая информация от клиента',
               existing_nullable=True)
    op.alter_column('raports', 'exists',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='Флаг отвечает существование файла в файловой системе, не удалять, потому что отчет можно восстановить по raw_data',
               existing_nullable=True)
    op.alter_column('raports', 'uuid',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36),
               comment=None,
               existing_comment='уникальный ключ рапорта',
               existing_nullable=True)
    # ### end Alembic commands ###
