"""empty message

Revision ID: d6133c78833f
Revises: 0e99b21f114a
Create Date: 2024-07-17 16:01:59.274666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6133c78833f'
down_revision: Union[str, None] = '0e99b21f114a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raports', sa.Column('key', sa.String(length=32), nullable=True, comment='Ключ к листу подбора'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raports', 'key')
    # ### end Alembic commands ###
