"""empty message

Revision ID: d660ede04ea8
Revises: f8f291df6af7
Create Date: 2024-06-20 17:16:28.808170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd660ede04ea8'
down_revision: Union[str, None] = 'f8f291df6af7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pattern', sa.String(length=128), nullable=False, comment='ссылка на название шаблона'),
    sa.Column('date', sa.DateTime(), nullable=True, comment='дата создания рапорта'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('clients', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Разрешение на чтение чужих рапортов',
               existing_comment='Разрешение чтения чужих рапортов',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               comment='Разрешение чтения чужих рапортов',
               existing_comment='Разрешение на чтение чужих рапортов',
               existing_nullable=True)
    op.drop_table('raports')
    # ### end Alembic commands ###
