"""empty message

Revision ID: e16064426a46
Revises: 52f7d39fdb6d
Create Date: 2024-07-26 17:18:29.094825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e16064426a46'
down_revision: Union[str, None] = '52f7d39fdb6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clients', 'company_name',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_comment='название компании клиента',
               existing_nullable=True)
    op.alter_column('clients', 'adress',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_comment='адрес у клиента',
               existing_nullable=True)
    op.add_column('raports', sa.Column('last_requests', sa.DateTime(), nullable=True, comment='последнего запроса'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raports', 'last_requests')
    op.alter_column('clients', 'adress',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=128),
               existing_comment='адрес у клиента',
               existing_nullable=True)
    op.alter_column('clients', 'company_name',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=128),
               existing_comment='название компании клиента',
               existing_nullable=True)
    # ### end Alembic commands ###
