"""empty message

Revision ID: f8f291df6af7
Revises: 99124e90d518
Create Date: 2024-06-20 15:32:34.755957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8f291df6af7'
down_revision: Union[str, None] = '99124e90d518'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('is_admin', sa.Boolean(), nullable=True, comment='Разрешение чтения чужих рапортов'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'is_admin')
    # ### end Alembic commands ###
