"""empty message

Revision ID: fe3c0b3ac673
Revises: 71165c2526a5
Create Date: 2024-07-03 21:09:14.953635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'fe3c0b3ac673'
down_revision: Union[str, None] = '71165c2526a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('first_name', sa.String(length=128), nullable=True, comment='имя клиента'))
    op.add_column('clients', sa.Column('last_name', sa.String(length=128), nullable=True, comment='фамилия клиента'))
    op.add_column('clients', sa.Column('father_name', sa.String(length=128), nullable=True, comment='отчество клиента'))
    op.add_column('clients', sa.Column('facility_name', sa.String(length=128), nullable=True, comment='название обьекта клиента'))
    op.drop_column('clients', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True, comment='имя клиента'))
    op.drop_column('clients', 'facility_name')
    op.drop_column('clients', 'father_name')
    op.drop_column('clients', 'last_name')
    op.drop_column('clients', 'first_name')
    # ### end Alembic commands ###
